(function() {
  /**
   * Created by happy on 3/23/17.
   */
  var assert, debug, gqcoffee, o;

  debug = require('debug')('http');

  assert = require('assert');

  gqcoffee = require('../lib/main.js');

  o = {
    version: "1.0"
  };

  describe('default', function() {
    it('should be able to load coffees', function(done) {
      gqcoffee.load(o, function(e, o) {
        global.coffee = o.result;
        console.log('global.coffee');
        console.log(JSON.stringify(coffee, null, 2));
        console.log('executing b');
        eval(coffee['coffee/sub/b']);
        console.log('b=' + b);
        assert(b === 456);
        done(e);
      });
    });
    it('should be able to load modules', function(done) {
      var c;
      // requirefromstring module pipe through. Use this gem to require a module written in coffee
      c = gqcoffee.requireFromString(coffee['coffee/requiretest']);
      assert(c.c === 789);
      done();
    });
    it('should be able to load coffees using q_load', function(done) {
      gqcoffee.q_load().then(function() {
        // q_load does exactly the same thing as first test except it is q_tree compliant
        eval(coffee['coffee/sub/b']);
        console.log('b=' + b);
        assert(b === 456);
      }).done(done);
    });
    return it('should be able to render with pass-in values', function(done) {
      return gqcoffee.q_load({
        option: {
          o1: "ddd",
          nominify: false
        }
      }).then(function(o) {
        return console.log(o.result);
      }).done(done);
    });
  });

  // ---
// generated by js2coffee 2.2.0

}).call(this);
